FROM rust:latest AS builder
WORKDIR /app

COPY Cargo.toml .
COPY src src
COPY migration migration
COPY entity entity
RUN cargo build --release

RUN strip target/release/sl_api

FROM gcr.io/distroless/cc-debian12:latest as release
WORKDIR /app
COPY --from=builder /app/target/release/sl_api .

EXPOSE 8000

CMD ["./sl_api"]
