//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "activity")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub hours: i32,
    pub name: String,
    pub color: String,
    pub day_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::day::Entity",
        from = "Column::DayId",
        to = "super::day::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Day,
}

impl Related<super::day::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Day.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
